services:
  django:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: stocktracker_django
    command: /start

    volumes:
      - .:/app
    ports:
      - 8010:8000
    # env_file is used to manage the env variables of our project
    env_file:
      - .env
    depends_on:
      - redis

  redis:
    image: redis:7-alpine
    restart: always

  celery_beat:
    build:
      context: .
      dockerfile: ./compose/local/django/Dockerfile
    image: stocktracker_celery_beat
    command: /start-celerybeat
    volumes:
      - .:/app
    depends_on:
      - redis
