# Generated by Django 4.2.4 on 2023-08-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticker", models.CharField(max_length=10)),
                ("open", models.FloatField()),
                ("close", models.FloatField()),
                ("volume", models.IntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
