# Generated by Django 4.2.4 on 2023-08-09 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0002_stock_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stock",
            name="close",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="date",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="open",
        ),
        migrations.RemoveField(
            model_name="stock",
            name="volume",
        ),
        migrations.AddField(
            model_name="stock",
            name="datetime",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 9, 15, 45, 21, 527916)
            ),
            preserve_default=False,
        ),
    ]
