# Generated by Django 4.2.4 on 2023-08-09 15:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stocks", "0003_remove_stock_close_remove_stock_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="ticker",
            field=models.CharField(max_length=5),
        ),
    ]
